react validated input
louiewhitz/rc0822-code-solutions pull request #119
Opened 2022-10-28 23:01 UTC by louiewhitz

https://user-images.githubusercontent.com/99847558/198748384-ee65868e-af06-45af-9b4e-ab4041468827.mov

2022-10-28 23:32 UTC, TimelikeClosure requested changes

2022-10-28 23:32 UTC, TimelikeClosure commented on react-validated-input-component/src/validated-input.jsx
> +  }
It doesn't look like you're using `isValid` or `errorMessage` in state, so I'd suggest removing them.

2022-10-29 01:01 UTC, louiewhitz commented
https://user-images.githubusercontent.com/99847558/198754741-1ab1688b-f06f-41a9-8311-bec180776ddb.mov

2022-10-31 17:26 UTC, scbowler requested changes
Looking good, just one update needed. Let me know if you have any questions.

2022-10-31 17:26 UTC, scbowler commented on react-validated-input-component/src/validated-input.jsx
> +    }
This code doesn't seem to really be doing anything. Here you only need the `setState` call to update `password` in state, nothing else is needed in this method.

2022-10-31 17:50 UTC, louiewhitz commented
https://user-images.githubusercontent.com/99847558/199075355-e7846696-45e9-4ee2-8606-a01716aee678.mov

2022-10-31 18:23 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-10-31 18:23 UTC, merged